### ISSUE TITLE
1.3.0 - External midi controller note priority

### ISSUE THREAD

**Issue by Intothegroove** [polyend/TrackerIssues#634] opened 2021-01-03 12:57 UTC
When using an external midi keyboard, the last held note or notes don't remain in play when you release other notes. Say you play the C key and then play the C key an octave up, when you release the first C key, it still plays even though you have the higher C key pressed down. It should be playing the last held key/note. 

* How often does this bug happen? every time

* Does this bug happen in previous firmware versions? Yes

* Does this bug happen in every project? Yes

**Comment by ambv** [comment] 2021-01-19 01:04
Duplicate of #151. This is fixed in 1.3.1b3 (to be released).

**Closed by ambv** 2021-01-19 01:04 UTC
Labels: bug
