### ISSUE TITLE
[Firmware version] Rendering issue

### ISSUE THREAD

**Issue by ZonashiSensei** [polyend/TrackerIssues#1089] opened 2021-06-07 15:17 UTC
hey I’m I’ve been having a problem with rendering samples on The tracker. I’m not sure if it’s because I have too much audio in my recorded samples folder but every time I try to render, it only samples about a few seconds from a random point. This is something that is happening very often wit me. About 6 times out of 10 when I try to render. This situation never came up in previous firmware for me. That’s why I’m thinking it is due to me not having enough space in the recorded samples area. This rendering situation happens in every project. 

Thank you!!! love the tracker so much!!!!

**Comment by ziej8asek** [comment] 2021-11-10 13:54
Duplicate of #1162

**Closed** 2021-11-10 13:54 UTC
Labels: bug, bug confirmed, fixed
