### ISSUE TITLE
1.4.0 Every time I go into the menu to try to disable the LFO or change the speed, the unit freezes.

### ISSUE THREAD

**Issue by Jacknametrouble** [polyend/TrackerIssues#1300] opened 2021-12-04 20:50 UTC
From Philip Meyer email: ntrm@inter-modal.com

"Hi I have a one-shot instrument and in the 2nd instrument parameters screen I've set the panning to be modulated by a random LFO at the fastest speed /128, which causes the unit to stop running and if the sequencer is running, it outputs a constant oscillator tone. The only way to stop it is to unplug the power cord and restart the unit. Every time I go into the menu to try to disable the LFO or change the speed, the unit freezes."

**Comment by k4ot** [comment] 2021-12-13 08:04
Try another power+USB cable. If it still makes the error, RMA

**Comment by ambv** [comment] 2021-12-18 18:57
Looks like a duplicate of fixed bug #903, let me know if you still have trouble after trying out [1.5.0b1](https://github.com/polyend/TrackerIssues/releases/tag/1.5.0b1).

**Closed by ambv** 2021-12-18 18:57 UTC
Labels: bug, cannot reproduce
