### ISSUE TITLE
[1.1.15] It may not be possible to add slots in song mode.

### ISSUE THREAD

**Issue by modmodmodmod** [polyend/TrackerIssues#60] opened 2020-09-20 06:19 UTC
The frequency was about once an hour.
 So far it has been confirmed in only one project.

In the video linked below, it disappeared as I went back and forth between other screens, but the pattern mode display is also strange.  There were times when it froze in this state and the power could not be turned off.  At that time, I unplugged the power cable and restarted, and it worked.

[https://drive.google.com/file/d/1r6W4ZLnM_rWrjMdWu_ZaXIX0pSffmKR0/view?usp=drivesdk](https://drive.google.com/file/d/1r6W4ZLnM_rWrjMdWu_ZaXIX0pSffmKR0/view?usp=drivesdk)

**Comment by pigeonsky** [comment] 2020-09-20 15:36
Reverted back to v1.1.0 and its working in this version. THEN, went to v.1.1.12 and now the PT is stuck on the load screen (just showing the logo...)
Help?

**Comment by piotr3500** [comment] 2020-09-21 08:49
Sometimes screen buttons (3 and 4) freeze. It's not only related with Song screen, it's in every screen. 
We're on it.

**Comment by piotr3500** [comment] 2020-09-21 11:46
Duplicate of #67

**Closed** 2020-09-21 11:47 UTC
Labels: bug, bug confirmed, duplicate, fixed
