### ISSUE TITLE
1.1.22 Tracker freeze in Song mode

### ISSUE THREAD

**Issue by stevesomeone** [polyend/TrackerIssues#199] opened 2020-10-11 01:24 UTC
Testing the new Song mode implementation. (red and green modes).
Tracker freezes totally
1. Enter song mode
2. shift between green and red modes.
3. on the third shift, the tracker sequencer stopped and froze. no response from any button and will not start.
4. Will not respond to power off via the proper manner (power button) requires you to pull out the usb power cable to reboot.

* How often does this bug happen? Every instance of entering song mode and changing between green/red.

* Does this bug happen in previous firmware versions? No

* Does this bug happen in every project? Yes

**Comment by piotr3500** [comment] 2020-10-11 17:21
I can't reproduce it. A video would give us more hints.

**Comment by ambv** [comment] 2020-10-11 17:27
I also cannot reproduce it.

**Comment by Jacknametrouble** [comment] 2020-10-11 20:21
Are you using external MIDI clock over USB maybe?

**Comment by stevesomeone** [comment] 2020-10-11 23:12
I have updated with links to 2 videos.
After more investigation, this appears to be an issue with external midi clock/transport.
You can see both; the inability to record info; and the random recording onto different tracks.
In a second video, you can see that you cannot step back to step rec mode.

https://www.dropbox.com/s/rv9q54wxrabivuf/Live%20rec%20bug%201.mp4?dl=0
https://www.dropbox.com/s/xpngjy0py0outna/Live%20rec%20bug%202.mp4?dl=0

**Comment by ambv** [comment] 2020-10-12 18:25
I can reproduce this.

**Comment by piotr3500** [comment] 2020-10-16 20:21
fixed in 1.1.23

**Closed** 2020-10-23 14:55 UTC
Labels: bug, bug confirmed, fixed, question
