### ISSUE TITLE
[1.4.0b3] Inconsistent render selection 

### ISSUE THREAD

**Issue by darenager** [polyend/TrackerIssues#1162] opened 2021-07-17 13:43 UTC
When rendering a selection the results are incorrect and inconsistent each time.

### Steps to reproduce

Highlight a selection you want to render, I used a whole track of 32 steps, went to top and used select all, shift+up.

Then render to selection, I noticed that not all steps had been rendered, repeat render to selection, again not all steps were rendered but different than last time with exact same selection, tried again and different again. After a few more attempts it rendered correctly, I continued repeating and the results were again inconsistent.

The easiest way to verify this bug is to do the first render, then go to the rendered file in the browser (exports/song name/selection) then after each render attempt go back to the sample loader and the new renders will be here to preview, I just used default names selection001 etc.

* How often does this bug happen? (every time, often, "it only happened once") Most of the time.

* Does this bug happen in previous firmware versions? Not sure

* Does this bug happen in every project? Yes, I tested a few and it happened on them all.

**Comment by joeyfivecents** [comment] 2021-07-18 23:58
This happens to me too. It takes 4 or 5 attempts to get the selection rendered correctly.

**Comment by trutypesounds** [comment] 2021-09-26 20:59
its the same on 1.4.0

**Comment by ziej8asek** [comment] 2021-11-10 13:56
Duplicate of #1251

**Closed by ziej8asek** 2021-11-10 13:56 UTC
Labels: bug, bug confirmed
