### ISSUE TITLE
[1.2.0] Rendering Is Resulting in All Unmuted Audio Being Reproduced In The New Sample

### ISSUE THREAD

**Issue by StellarTrash** [polyend/TrackerIssues#290] opened 2020-10-25 00:58 UTC
### Steps to reproduce:  Highlight two samples in adjacent tracks.  Render Selection.  All audio on all tracks is reproduced in the new sample regardless of samples selected.  I've never seen this happen before 1.20.  Have rendered plenty of samples together.

It's late and I can't turn my monitors on, but will try and get video and audio tomorrow.

### Attachments and links

Often the best way to show the problem is to record a short video,
attach the Tracker project you were working on, and provide links.

Pro-tip: You can drag and drop images and `.zip` files directly to the edit
box when writing your bug reports. Videos are too big as attachments, you
will have to use an external service for this and provide us links. Please
don't use services that delete files after short periods of time.

### Other important information

* How often does this bug happen? Every time I've tried it so far.  

* Does this bug happen in previous firmware versions?  Not that I've noticed.

* Does this bug happen in every project?  Not sure yet.

**Comment by Jacknametrouble** [comment] 2020-11-02 13:55
Duplicate of #321

**Closed by Jacknametrouble** 2020-11-02 13:55 UTC
Labels: bug, bug confirmed
