### ISSUE TITLE
[1.2.1] All buttons freeze (at least in song mode and config window)

### ISSUE THREAD

**Issue by LetsSeeIfWeSolveThis** [polyend/TrackerIssues#317] opened 2020-10-30 16:11 UTC
At the moment I don't know how to recreate it, but it happened yesterday in config window and just happened now in song mode.

Every button does not respond, but the wheel does, also the pads and the on/off button (it shows the shutting down message perfectly)

Even with a restart, the problem persisted only till I remove and reconnect the USB wire. I just tried right now to restart more than one time, but the problem didn't leave just repeating this action. The only way was removing and reconnecting the wire.

**Comment by Jacknametrouble** [comment] 2020-11-02 13:53
Duplicate of #294

**Closed by Jacknametrouble** 2020-11-02 13:53 UTC
Labels: bug
