### ISSUE TITLE
Sample Purge

### ISSUE THREAD

**Issue by TwistedGenetics** [polyend/TrackerIssues#416] opened 2020-11-25 14:14 UTC
Hi

It would be cool to either, have a marker in the "sample Loader" section to show currently used samples, or an option to purge unused samples from the instruments pool.

**Comment by mroemore** [comment] 2020-11-25 16:43
I agree, but this is a duplicate of issue #396

**Comment by PaulAntioche** [comment] 2020-11-27 16:31
yes!

**Comment by jaap3** [comment] 2020-12-27 19:29
Firmware 1.3.0 adds a "Delete unused" button to the sample loader screen

**Comment by Jacknametrouble** [comment] 2021-12-18 19:50
This has been added in 1.3.0

**Closed by Jacknametrouble** 2021-12-18 19:50 UTC
Labels: enhancement
