### ISSUE TITLE
[1.2.1] Now the freeze part are the pads in every window.

### ISSUE THREAD

**Issue by LetsSeeIfWeSolveThis** [polyend/TrackerIssues#318] opened 2020-10-31 15:39 UTC
All works but the pads, exactly the same behavior described in #317 but this time only the pads stopped working. I cannot introduce any note or effect value, nothing. I tried restarting once and twice but the problem persist.

Again it got solved removing and reconnecting the USB power wire. Same solution as in my last issue reported #317

**Comment by Jacknametrouble** [comment] 2020-11-02 13:36
Duplicate of #317

**Closed by Jacknametrouble** 2020-11-02 13:36 UTC
Labels: bug
