### ISSUE TITLE
[1.2.0] Pattern Stems do not export correctly (tempo + length)

### ISSUE THREAD

**Issue by clickysteve** [polyend/TrackerIssues#297] opened 2020-10-26 01:36 UTC
### Steps to reproduce

When exporting stems from a pattern, they all end at different lengths. This suggests a tempo issue (as in https://github.com/polyend/TrackerIssues/issues/281). 

If not a tempo issue, then the patterns should include the empty space at the end of the pattern so they match up correctly in length when exported.

### Attachments and links

Potentially related to: https://github.com/polyend/TrackerIssues/issues/281

<img width="389" alt="Screen Shot 2020-10-26 at 01 23 22" src="https://user-images.githubusercontent.com/6227598/97125389-b43f1e00-172b-11eb-910b-5a755c133076.png">

### Other important information

This happens with no effects, no micro-timing, and short pattern lengths. I have not tested it with previous firmware versions.

**Comment by Jacknametrouble** [comment] 2020-11-02 14:14
Duplicate of #281

**Closed by Jacknametrouble** 2020-11-02 14:14 UTC
Labels: bug
