### ISSUE TITLE
[1.4.0] Beat slices not fully displaying

### ISSUE THREAD

**Issue by jcnrn** [polyend/TrackerIssues#1205] opened 2021-08-27 01:24 UTC
[1.3.1] Added beat slices to auto slice function not displaying after "Normalize" effect

### Steps to reproduce

1. Load sample (was using an Amen Break),
2. Switch to "Sample Playback" view,
2. Select "Beat Slice," 
3. Use "Auto Slice," 
4. Add manual slices to the sample, 
5. Saved project as "amenStart"
5. Switch to "Sample Editor" view,
6. Apply "Normalizer" effect with default settings, and
7. Switch back to "Sample Playback."
8. Added beat slices are now invisible.

### Attachments and links
https://photos.app.goo.gl/VMuwSXYWPcfgv4tv6

### Other important information

* How often does this bug happen? (every time, often, "it only happened once")
I was not able to reproduce the bug by reloading my saved file. Only happened once.

* Does this bug happen in previous firmware versions?
Unsure

* Does this bug happen in every project?
Will pay attention going forward

**Comment by cmezak** [comment] 2021-11-07 21:57
I'm seeing what might be a duplicate of this bug. I'm playing with the DJMastacut Foamy Value sample project from the Polyend blog. To see what's going on, I've been switching between instruments while the Sample Playback screen is up. If I switch from an instrument that is not using Beat Slice to one that is, the Slice markers are not visible until I select a different slice or adjust the currently selected slice.

**Comment by cmezak** [comment] 2021-11-12 18:56
@jcnrn Let me know if you would like a new issue report specifying v1.4.0 and with a video.

**Comment by jcnrn** [comment] 2021-11-15 14:40
Hey @cmezak,

I've been trying to reproduce and not seeing. Yeah, if you want to add here I can update the title to 1.4.0.

Joe

**Comment by ziej8asek** [comment] 2021-11-25 16:29
Something similar happens when the zoom in Sample Playback is changed before switching to the instrument that is using Beat Slice. Could this be that issue?

**Closed** 2021-12-18 13:20 UTC
Labels: bug, fixed
