### ISSUE TITLE
[1.3.0] File > Games with empty Games folder crashes Tracker

### ISSUE THREAD

**Issue by tilllt** [polyend/TrackerIssues#585] opened 2020-12-25 16:46 UTC
### Steps to reproduce
Tap Files, Tap Games -> Crash

EDIT: It seems its not a crash but the inability to exit the game menu, as described here:
https://github.com/polyend/TrackerIssues/issues/596

**Comment by tilllt** [comment] 2020-12-27 14:07
https://youtu.be/UvU5q3BgYeU

**Comment by phaelam** [comment] 2020-12-28 00:29
perhaps if the games folder is going to be part of the install....it might be best there is something in it so it doesn't crash. I checked to see if anything came with the update. and in doing so, as its empty it crashed. no need for games...deleted folder

**Comment by tilllt** [comment] 2020-12-28 10:21
As mentioned here
https://github.com/polyend/TrackerIssues/issues/596

Apparently it doesn't crash, there is just nothing you can do in the games menu when you haven't installed the games. The bug is that you cannot exit the menu in any way.

**Comment by phaelam** [comment] 2020-12-28 20:12
Being stuck there not being able to do anything is equivalent to a crash.

**Comment by ziej8asek** [comment] 2021-01-04 14:43
Duplicate of #596

**Closed** 2021-01-04 14:43 UTC
Labels: bug, fixed
