### ISSUE TITLE
Default attack set to 0 instead of 0,10ms

### ISSUE THREAD

**Issue by HakkahFR** [polyend/TrackerIssues#125] opened 2020-10-03 11:31 UTC
Hello,the envellope default attack is set to 0,10 ms. It's change a lot the sound of percussion samples. If you can set by 0ms the default attack it could be better

**Comment by ambv** [comment] 2020-10-03 11:36
Thanks for reporting! This is a duplicate of https://github.com/polyend/TrackerIssues/issues/85 and is already fixed for the upcoming beta.

**Closed by ambv** 2020-10-03 11:36 UTC
Labels: enhancement
