### ISSUE TITLE
1.1.23 Instrument playback/preview issue

### ISSUE THREAD

**Issue by stevesomeone** [polyend/TrackerIssues#238] opened 2020-10-17 07:02 UTC
Video attached.
Very simple setup to illustrate the problem.
I have a track with a short sample on 2 steps.
If I try also to play any sample with the pads, there is no audio from the 'free playing sample'
This is present in Both Pattern screen and Playback screen.
I do not believe that there should be any polyphony choking with the samples I have chosen to demonstrate.

* How often does this bug happen? Very often
* Does this bug happen in previous firmware versions? It is quite similar to previously reported bugs regarding sample previewing and voicing, but not exactly the same.
* Does this bug happen in every project? Yes

https://www.dropbox.com/s/9bj6kteoik7qp64/1.1.23%20Instrument%20preview%20and%20playback%20issue.mp4?dl=0

**Comment by piotr3500** [comment] 2020-10-17 13:01
Duplicate of #244

**Closed by piotr3500** 2020-10-17 13:01 UTC
Labels: bug, duplicate
