### ISSUE TITLE
MicroPitch is interesting, but can we add a regular Pitch shift?

### ISSUE THREAD

**Issue by MachineAgeVoodoo** [polyend/TrackerIssues#320] opened 2020-10-31 22:21 UTC
Hi. The title says it all, an FX that simply pitches in increments of semitones seems to be missing. Apologies if I am missing something obvious. A sample as it plays through the pattern, could be pitched up or down per step. Then not only by retriggering it on a new key. This could then also be used to achieve "pitch bend" type of effects.

Thank you for reading

**Comment by ROM72** [comment] 2020-11-01 16:54
Yes, a pitch envelope would be great and not just a finetune envelope.

**Comment by dmt-hub** [comment] 2020-11-02 10:19
Yes, please!

**Comment by tfspsound** [comment] 2020-11-19 13:43
Totally onboard with this, it’d save copying samples to repitch them too.

**Comment by nthe** [comment] 2021-03-02 19:47
I would that as well, but it looks like this one was already requested and rejected. 😞

Duplicate of #344

**Comment by MachineAgeVoodoo** [comment] 2021-03-02 20:26
its implemented already in current firmware

**Comment by nthe** [comment] 2021-03-03 05:58
I was reffering to pitch envelope feature in automation panel, or am I missing something? 🤔

I see that the ticket is just about pitch shift and not about automation.... sorry for confusion. 😐

**Comment by Jacknametrouble** [comment] 2021-03-03 09:39
This isn't possible due to the used hardware resources.

**Closed by Jacknametrouble** 2021-03-03 09:39 UTC
Labels: enhancement
