### ISSUE TITLE
[1.1.14] Tracker freeze when preview WT Smoother with a window Num set to 1.

### ISSUE THREAD

**Issue by Jacknametrouble** [polyend/TrackerIssues#45] opened 2020-09-16 13:10 UTC
Tracker did freeze when preview WT Smoother with a Window Num set to 1

* How often does this bug happen? (every time, often, "it only happened once") - always,

* Does this bug happen in previous firmware versions? - don't know,

* Does this bug happen in every project? - every project,

**Comment by ziej8asek** [comment] 2020-09-18 12:55
Duplicate of #

**Closed by ziej8asek** 2020-09-18 12:55 UTC
Labels: bug, bug confirmed, fixed
