### ISSUE TITLE
[1.1.15]Unstable behavior of sample playback

### ISSUE THREAD

**Issue by modmodmodmod** [polyend/TrackerIssues#54] opened 2020-09-19 07:31 UTC
Perhaps this is due to the pattern I entered, but sometimes I couldn't select end point on the sample playback page.  The sample may also be previewed when  I try to select endpoint.  I couldn't reproduce it when I shot the attached video, but when I returned to the pattern screen from this state, it was displayed several times as if the columns other than the current column were empty.

Please refer to the attached video.

[https://drive.google.com/file/d/15R1A68XEcN_4CePkrdLX3lmR47IokB8L/view?usp=drivesdk](https://drive.google.com/file/d/15R1A68XEcN_4CePkrdLX3lmR47IokB8L/view?usp=drivesdk)

**Comment by piotr3500** [comment] 2020-09-21 11:47
Duplicate of #67

**Closed by piotr3500** 2020-09-21 11:47 UTC
Labels: bug, bug confirmed, duplicate, fixed
