### ISSUE TITLE
[1.3.0] High pitched noise in all audio output

### ISSUE THREAD

**Issue by mfroach** [polyend/TrackerIssues#712] opened 2021-01-18 20:40 UTC
> After updating to 1.3.0 firmware, at all times there is a subtle high
> pitch noise from audio output. When line in monitor is on it is significantly
> louder, and master volume affects the volume of the noise.

**Comment by PEtajaja** [comment] 2021-01-18 20:45
Out of curiosity, does the noise stop when you unplug everything?

**Comment by mfroach** [comment] 2021-01-18 20:47
When removing the line out , yes the audio stops playing and I cannot hear the noise anymore

**Comment by PEtajaja** [comment] 2021-01-18 21:50
Should've been clearer, remove everything and listen via headphones rather than through an interface / mixer etc.

I've had similar issues with gear before that ended up being the result of a ground loop or usb noise, if it was to go away by doing the above, could it be you changed anything else?

Obviously if the issue stays then it's caused by the update

**Comment by doelman** [comment] 2021-01-18 21:58
For me since 1.3 the Tracker actually outputs a buzzing sound when it's switched off (but plugged in, obviously). Dissapears as soon as I switch the unit on

**Comment by mfroach** [comment] 2021-01-18 22:00
Ah, yes, the issue remains with direct headphone connection. I have also tried swapping 3.5 cable  resetting firmware (1.3 again), with no luck. This didn’t happen before firmware update. Also, the noise only starts once the device had played some audio(playing a pattern or sample)

**Comment by mfroach** [comment] 2021-01-19 00:19
Am curious if this is related to this new feature;
> Live Audio Line Input Monitoring is now available during song playback

**Comment by mfroach** [comment] 2021-01-19 00:28
Muting all tracks and line in gets rids of the noise. So not a hardware issue I think.

**Comment by ambv** [comment] 2021-01-19 00:40
Does muting Line In only get rid of the noise as well? Not sure how muting other tracks can affect noise when not playing anything.

**Comment by mfroach** [comment] 2021-01-19 03:57
Muting line in gets rid of some of the noise , muting the tracks with notes on them gets rid of all the noise. Also for clarification I’ve managed to make this barely noticeable by setting master volume to ~25db and turning up volume for dry mix

**Comment by t8pt** [comment] 2021-01-19 14:44
Had this problem with constant background noise after recording from line in, too.
Newly created projects suffer from this background noise. When opening one of the pre-made projects made by other artists the static noise is not present. Very strange is that if I change the display brightness to max the noise is gone, too. After fooling around a bit I found a temporary workaround: I reverted the firmware to 1.2.0, created a init project (without any background noise), updated to 1.3.0 and use this init project as a starting point.

**Comment by t8pt** [comment] 2021-01-19 16:43
To be honest I'm questioning if this static noise from the line in is solely software dependent. Could there be some kind of hardware problem?

**Comment by t8pt** [comment] 2021-01-19 18:34
Checked again - line in noise is severely reduced after changing the display brightness from low to high. Not good because this feels like it's an electronic hardware based problem...

**Comment by anemlife** [comment] 2021-01-20 11:27
> Checked again - line in noise is severely reduced after changing the display brightness from low to high. Not good because this feels like it's an electronic hardware based problem...

Maybe not related but I had some similar issues with my modular system when plugged at home (old house, bad installation). Got rid of all the digital noises by using a D.I. box. In my current setup the tracker output is plugged to the modular then to the D.I. box then to my soundcard and it feels ok about the noises! Maybe try a D.I. box? 

Also I always keep the tracker master level between -20db and 0db and then I boost it with external gear because when I go up to 0db internally I do notice some noise! But boosting it after sounds better in my opinion.

Just curious but what are you using to power the Tracker?

**Comment by t8pt** [comment] 2021-01-20 19:46
> Just curious but what are you using to power the Tracker?

Wall mount and USB power bank. The issue occurs with both and at different places (old house, new house, etc.).

**Comment by tinysynths** [comment] 2021-01-20 23:33
Same issue here. The Tracker line out is nearly completely silent (in fact better signal to noise than many products - it is great). However, when line in is active both for monitoring and when recording samples there is a very annoying high pitched noise. I've tested without anything plugged into the line in and with various synths/instruments plugged in. The high pitched noise gets recorded to the signal and makes the sounds unusable. Pitch shifting a sample recorded via the line in makes the noise even more present.

I have run various tests and it does not seem to be a ground loop issue. I have run similar tests with my eurorack, Elektron devices, microfreak, outboard gear, guitar pedals etc. Only the Tracker exhibits this noise (when line in is active).

I have tested powering the Tracker using battery packs, usb hub, usb c port on laptop and wall adaptor. The noise issue doesn't change or get affected by different power sources and is always present.

Attached is a screenshot of the noise.

![Screenshot 2021-01-20 at 23 20 12](https://user-images.githubusercontent.com/65287761/105253581-ad337a80-5b77-11eb-8195-16e1113bd360.png)

It would be great to get this issue fixed so we can record noise free samples.

Thanks!

**Comment by t8pt** [comment] 2021-01-21 06:25
> Same issue here.

Do different settings of display brightness change anything?

**Comment by mfroach** [comment] 2021-01-21 18:26
> Very strange is that if I change the display brightness to max the noise is gone, too

can confirm on my machine this lowers the volume of the noise (does not get rid of it completely.)on low brightness it’s much louder. And fun fact, my bluetooth speaker suddenly gets the same noise when I change brightness to low. I don’t hook the speaker up to the tracker. Seems like the display is causing some kind of RF noise??

**Comment by CV-Gate** [comment] 2021-01-22 11:32
I never had this issue but, in my case, I always power from a power bank. Maybe related?

**Comment by thebradclay** [comment] 2021-01-22 13:15
@CV-Gate  it has been mentioned by @t8pt that the issue persists even with a power bank,
"Wall mount and USB **power bank**. The issue occurs with both and at different places (old house, new house, etc.).".

**Comment by topoexplo** [comment] 2021-01-29 04:05
I’m also experiencing this issue. The noise is high pitched and wavy. And yes, the issue is not as bad when I change the screen brightness to high.

**Comment by gurkenkimchi** [comment] 2021-01-29 09:56
i can confirm this issue too. is there going to be a fix for it or its mainly a hardware issue ?

**Comment by t8pt** [comment] 2021-01-29 14:41
> is there going to be a fix for it or its mainly a hardware issue ?

the question!

**Comment by t8pt** [comment] 2021-02-20 20:01
the question still remains...

**Comment by mfroach** [comment] 2021-02-20 20:18
> the question still remains...

@t8pt to be fair the issue is possibly unfixable and pretty negligible. since it seems like the display is causing the noise it could require a hardware fix. Plus i don’t notice it at all once lowering master volume. would prefer it gone but I’ll be patient

**Comment by ambv** [comment] 2021-02-28 14:13
This is indeed display brightness related and is fixed in 1.3.1 beta 4.

**Closed by ambv** 2021-02-28 14:13 UTC
Labels: bug

**Comment by demolen** [comment] 2021-12-03 08:23
This is not fixed in 1.4.0 or at least regressed.
