### ISSUE TITLE
[1.1.15] Export Song - Clicks

### ISSUE THREAD

**Issue by MegaTurrican** [polyend/TrackerIssues#62] opened 2020-09-20 10:26 UTC
I've been trying to export a track clean but unfortunately I get lots of clicks / sample start envelope crackles, on the final wav.
The clicks are also heard during playback actually. There is a lot going on in the track, so I attached it for reference.

Same clicking issues have been occurring in all firmware versions in this track, with only exception the 1.1.0 version (which we used this track for promo). It seems that busy tracks / dense sample alternations might cause this.
[qebo-002.zip](https://github.com/polyend/TrackerIssues/files/5251441/qebo-002.zip)

**Comment by piotr3500** [comment] 2020-09-22 12:03
Duplicate of #47

**Closed by piotr3500** 2020-09-22 12:03 UTC
Labels: bug, duplicate
